Tsocha/support for new aeon
NervanaSystems/deepspeech pull request #57
Opened 2017-09-25 07:23 UTC by tsocha

2017-09-25 17:39 UTC, jennifermyers commented
@tyler-nervana @Neuroschemata can you review this? We'd like to release neon 2.2 today if possible.

2017-09-25 17:42 UTC, wei-v-wang commented
This is to address https://github.com/NervanaSystems/private-neon/issues/1001

2017-09-25 18:15 UTC, tyler-nervana requested changes

2017-09-25 18:15 UTC, tyler-nervana commented on speech/train.py
> +train = make_loader(train_manifest, alphabet, nbands, max_tscrpt_len, backend_obj=be)
Can you make `max_utt_len` an argument here and pass it into `common_config`?

2017-09-25 18:15 UTC, tyler-nervana commented on speech/data/ingest_librispeech.py
> +import json
Unused import

2017-09-25 18:15 UTC, tyler-nervana commented on speech/data/ingest_librispeech.py
> +from neon.data.dataloaderadapter import DataLoaderAdapter
Unused import

2017-09-25 18:15 UTC, tyler-nervana commented on speech/data/ingest_librispeech.py
> +                            "sample_freq_hz": 16000,
Align `"sample_freq_hz"` and below with `"type"`.

2017-09-25 18:15 UTC, tyler-nervana commented on speech/data/ingest_librispeech.py
> +                                      "alphabet": alphabet,
Alignment here too

2017-09-26 05:57 UTC, tyler-nervana approved these changes

2017-09-26 05:59 UTC, merged